version: '2'
services:
  solr-master:
    build: .
    build:
      context: solr/master
      dockerfile: Dockerfile
    command: ["solr", "-f"]
    environment:
        SERVICE_NAME: 'solr-master'
        SERVICE_TAGS: 'solr-master'
        SERVICE_CHECK_HTTP: '/solr/sortdemo/select?rows=0&q=*:*'
        SERVICE_CHECK_INTERVAL: '5s'
  
  solr-slave:
    build:
          context: solr/slave
          dockerfile: Dockerfile
    command: ["solr", "-f"]
    links:
      - solr-master
    environment:
        SERVICE_NAME: 'solr-slave'
        SERVICE_TAGS: 'solr-slave'
        SERVICE_CHECK_HTTP: '/solr/sortdemo/select?rows=0&q=*:*'
        SERVICE_CHECK_INTERVAL: '5s'
